// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifemrlcngjpybfztfqji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmZW1ybGNuZ2pweWJmenRmcWppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxNzYzODIsImV4cCI6MjA1NDc1MjM4Mn0.ClBU6mDN8oxMkpveJGC8uVt2NdHCWKiag6dUzqw-lHI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);